name: dgca_tasks
channels:
  - conda-forge
dependencies:
  - python=3.10
  - graph-tool
  - tqdm
  - numpy
  - pandas  
  - pyarrow
  - scikit-learn
  - jsonpickle  
  - plotnine
  - networkx
  - jsonpickle
  - parallel
  - pip:
    - wrapt_timeout_decorator
    - multiset
    - reservoirpy
    - igraph
